from enum import StrEnum


ABOUT_MAX_LENGTH = 256
AVATAR_FONT_RATIO = 0.52
AVATAR_FORMAT = "PNG"
AVATAR_MODE = "RGB"
AVATAR_CONTENT_RATIO = 0.75
AVATAR_SIZE = 256
AVATAR_TEXT_FILL = "#ffffff"
DEFAULT_AVATAR_LETTER = "U"
EMAIL_MAX_LENGTH = 254
GITHUB_HOSTS = ("github.com", "www.github.com")
PAGE_SIZE = 12
PASSWORD_MAX_LENGTH = 128
PHONE_MAX_LENGTH = 12
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6
SKILL_NAME_MAX_LENGTH = 124
SKILLS_SUGGESTIONS_LIMIT = 10
MIN_FONT_SIZE = 1
USER_NAME_MAX_LENGTH = 124


class AvatarColor(StrEnum):
    BLUE = "#5B8DEF"
    GREEN = "#46A67E"
    TERRACOTTA = "#C77654"
    PURPLE = "#7B68B8"
    GOLD = "#D19A3A"


AVATAR_COLORS = tuple(color.value for color in AvatarColor)
